### ISSUE TITLE
error running quant3p

### ISSUE THREAD

**Issue by bhykes1** [ctlab/quant3p#3]
Hi, I am trying to run quant3p with the following command:

quant3p -n ATG5 -g [genome annotation file] *.bam

,but I keep getting the following error

pkg_resources.DistributionNotFound: quant3p==0.1
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "-".
_: line 2: ATG5.htseq/run_1856.R64_Yokoyama_mouse_874.CACATCCT.htseq.out: Permission denied
[bam_header_read] EOF marker is absent. The input is probably truncated.
Traceback (most recent call last):
  File "/usr/local/bin/fix-mm", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3023, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 614, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 920, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 807, in resolve
pkg_resources.DistributionNotFound: quant3p==0.1
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "-".
quant3p: Error on or near line 121; exiting with status 1

**Comment by assaron** [comment]
Did you check that the bam files are indeed in the current working directory?

**Comment by bhykes1** [comment]
It's turns out, it was just an installation error. 

thanks

**Comment by assaron** [comment]
Oh, OK
